ARG GOLANG_VERSION=1.26.1

FROM --platform=$BUILDPLATFORM golang:${GOLANG_VERSION}-alpine AS build

COPY . /src
WORKDIR /src

ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    apk add --no-cache make git && \
    make build && \
    rm -rf /var/cache/apk/*

FROM ghcr.io/wntrtech/scratch:latest
COPY --from=build /src/portainer-deploy-plugin /bin/portainer-deploy-plugin
ENTRYPOINT ["/bin/portainer-deploy-plugin"]