name: Pull request check

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Vendor + generate
        env:
          CGO_ENABLED: "0"
          GOPRIVATE: git.zzdats.lv
          PACKAGE_TOKEN: ${{ secrets.package_token }}
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          go mod vendor
          go generate ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1.0
          args: --timeout 3m --output.checkstyle.path golangci-lint.out --output.tab.path stdout

      - name: Lint Dockerfile
        run: docker run --rm -v $(pwd):/work hadolint/hadolint:latest-alpine hadolint /work/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (dry run)
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save image to tar
        run: docker save test -o ${{ github.event.repository.name }}.tar

      - name: Image security check
        run: |
          docker run --rm -v $(pwd):/work aquasec/trivy:0.69.3 image --exit-code 0 --severity UNKNOWN,LOW,MEDIUM --input /work/${{ github.event.repository.name }}.tar
          docker run --rm -v $(pwd):/work aquasec/trivy:0.69.3 image --exit-code 1 --severity HIGH,CRITICAL --input /work/${{ github.event.repository.name }}.tar